<a href="https://colab.research.google.com/github/furkan54777/My_Assignment/blob/master/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

In [ ]:
# Descriptive statistics summarizes or describes the characteristics of a data set.
# Descriptive statistics consists of two basic categories of measures: measures of central tendency and measures of variability (or spread).
# Measures of central tendency describe the center of a data set.
# Measures of variability or spread describe the dispersion of data within the set.

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import scipy as sns
import pandas as pd
from scipy import stats
from scipy.stats import skew
from scipy.stats import kurtosis

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

np.random.normal(loc=0.0, scale=1.0, size=None)  #you need to modify this code.

loc will be equal to mean, scale will be equal to std deviation, size will be equal to sample size.

In [ ]:
samples = np.random.normal(loc=100, scale=15, size=1000)

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print(mean)
print(median)
print(mode)

99.9245370399142
100.16695327880933
ModeResult(mode=array([50.77598148]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = stats.iqr(samples)
print(min)
print(max)
print(q1)
print(q3)
print(iqr)

50.77598148239014
148.61495839587076
89.96064413188564
110.19546395079728
20.23481981891163


In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)
print(variance)
print(std_dev)

230.49326277436637
15.18200457035784


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [ ]:
skewness = skew(samples)
kurtosis_ = kurtosis(samples)
print(skewness)
print(kurtosis_)

-0.136600781732687
0.052041117599658904


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([10, 25, 32, 45, 28, 19, 7, 12, 5, 54])
print(y)

[10 25 32 45 28 19  7 12  5 54]


**Once** you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x, y)
print(r)

[[1.         0.03680522]
 [0.03680522 1.        ]]


## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
from numpy.lib.function_base import corrcoef
r = corrcoef(x, y)
print(r)

[[1.         0.75864029]
 [0.75864029 1.        ]]


OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
from scipy import stats
rho = stats.spearmanr(x, y)
print(rho)

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)


## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
tips.corrwith(tips)

total_bill    1.0
tip           1.0
size          1.0
dtype: float64